name: nanolink-group
location: westeurope
type: Microsoft.ContainerInstance/containerGroups
properties:
    containers:
        - name: nanocaddy
          properties:
              image: ${CONTAINER_REGISTRY}/caddy:2.8.4
              command:
                [
                    'caddy',
                    'reverse-proxy',
                    '--from',
                    'nanolink.westeurope.azurecontainer.io',
                    '--to',
                    'localhost:8080',
                ]
              ports:
                  - port: 443
                    protocol: TCP
                  - port: 80
                    protocol: TCP
              resources:
                  requests:
                      cpu: 0.1
                      memoryInGB: 0.1
        - name: nanolink
          properties:
            image: ${CONTAINER_REGISTRY}/nanolink:latest
            ports:
            - port: 8080
              protocol: TCP
            environmentVariables:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            ### Now we read the connection strings from Key Vault:
            #- name: ConnectionStrings__UrlStoreConnection
            #  value: ${URL_STORE_CONNECTION_STRING}
            - name: PORT
              value: 8080
            resources:
              requests:
                memoryInGB: 0.1
                cpu: 0.1
              limits:
                memoryInGB: 0.1
                cpu: 0.1
    ipAddress:
        ports:
            - port: 443
              protocol: TCP
            - port: 80
              protocol: TCP
        type: Public
        dnsNameLabel: nanolink
    osType: Linux
    imageRegistryCredentials:
        - server: ${CONTAINER_REGISTRY}
          username: ${ACR_USERNAME}
          password: ${ACR_PASSWORD}